version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
    - 4.3.4
  - dependency-name: solhint
    versions:
    - 3.3.3
    - 3.3.4
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
  - dependency-name: ethereumjs-util
    versions:
    - 7.0.8
    - 7.0.9
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: "@openzeppelin/test-helpers"
    versions:
    - 0.5.10
  - dependency-name: "@openzeppelin/test-environment"
    versions:
    - 0.1.9
